version: "3.9"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env

  pgadmin:
    container_name: dploy_pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./.pgdata_pgadmin:/root/.pgadmin
    depends_on:
      - db

  api:
    restart: always
    env_file:
      - .env
    volumes:
      - .:/home/d-ploy/dploy
    ports:
      - "${API_PORT}:8000"
    depends_on:
      - db
