"""make aws tables

Revision ID: 4e3f9fb11a7f
Revises: 5d386c5381bb
Create Date: 2023-09-15 10:20:09.543864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3f9fb11a7f'
down_revision = '5d386c5381bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_keys',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('access_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column('secret_access_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        
        sa.ForeignKeyConstraint(["user_id"],["users.id"]),
        sa.PrimaryKeyConstraint('id', name='aws_keys_pkey')
    )

    op.create_table('aws_instances',
            sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column('user_id', sa.INTEGER(), autoincrement=False),
            sa.Column('instance_id', sa.INTEGER(), autoincrement=False, nullable=False),
            
            sa.ForeignKeyConstraint(["user_id"],["users.id"]),
            sa.PrimaryKeyConstraint('id', name="aws_instances_pkey")
            )
    
            

    
    op.create_table('aws_instance_keys',
            sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
            sa.Column('instance_id', sa.INTEGER()),
            sa.Column('key_name', sa.VARCHAR(length=255)),
            sa.Column('key_material', sa.VARCHAR(length=255)),

            sa.ForeignKeyConstraint(["instance_id"],["aws_instances.id"]),
            sa.PrimaryKeyConstraint('id', name='aws_instance_keys_pkey' )
            )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aws_keys')
    op.drop_table('aws_instances')
    op.drop_table('aws_instance_keys')
    # ### end Alembic commands ###
