"""make users table

Revision ID: 5d386c5381bb
Revises: 
Create Date: 2023-09-15 08:31:20.113207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d386c5381bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name",sa.String(255)),
        sa.Column("gender", sa.String(255)),
        sa.Column("email", sa.String(255)),
        sa.Column("password",sa.String(255)),
       

        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.drop_table("users")
    # ### end Alembic commands ###
